import { Edit, FileText, ImagePlus, Plus, Search, Trash2, X } from 'lucide-react'
import { FormEvent, useEffect, useMemo, useState } from 'react'

const API_BASE_URL = 'https://39production-api.39production.workers.dev'
const MAX_IMAGE_SIZE = 5 * 1024 * 1024
const MAX_STORED_IMAGE_SIZE = 150 * 1024
const ALLOWED_IMAGE_TYPES = ['image/jpeg', 'image/png', 'image/webp', 'image/gif']

interface News { id: number; title: string; category: string; author: string; excerpt: string; content: string; date: string; status: 'Published' | 'Draft'; image_url?: string | null; created_at?: string; updated_at?: string }
interface NewsForm { title: string; category: string; author: string; excerpt: string; content: string; date: string; status: 'Published' | 'Draft' }
interface ApiResponse<T> { success: boolean; message?: string; data?: T }
const emptyForm: NewsForm = { title: '', category: 'Company', author: 'Admin', excerpt: '', content: '', date: new Date().toISOString().split('T')[0], status: 'Published' }

function extractToken(value: unknown): string | null { if (typeof value === 'string') { const t = value.trim(); if (!t) return null; try { return extractToken(JSON.parse(t)) } catch { return t } } if (value && typeof value === 'object') { const r = value as Record<string, unknown>; for (const k of ['token', 'access_token', 'accessToken', 'admin_token', 'adminToken', 'session_token', 'sessionToken']) { const v = r[k]; if (typeof v === 'string' && v.trim()) return v.trim() } for (const k of ['data', 'auth', 'session', 'user']) { const v = extractToken(r[k]); if (v) return v } } return null }
function getStoredAuthTokens() { const tokens: string[] = []; const seen = new Set<string>(); const add = (v: unknown) => { const t = extractToken(v); if (t && !seen.has(t)) { seen.add(t); tokens.push(t) } }; const keys = ['token', 'auth_token', 'access_token', 'accessToken', 'admin_token', 'adminToken', 'session_token', 'sessionToken', 'auth', 'adminAuth', 'user']; for (const storage of [window.localStorage, window.sessionStorage]) { for (const k of keys) { try { add(storage.getItem(k)) } catch { } } try { for (let i = 0; i < storage.length; i++) { const k = storage.key(i); if (k && !keys.includes(k)) add(storage.getItem(k)) } } catch { } } return tokens }
async function getAdminToken() { for (const token of getStoredAuthTokens()) { try { const r = await fetch(`${API_BASE_URL}/api/auth/me`, { headers: { Authorization: `Bearer ${token}` }, cache: 'no-store' }); if (r.ok) return token } catch { } } return null }
async function adminFetch(url: string, init: RequestInit = {}) { const token = await getAdminToken(); if (!token) throw new Error('Admin session not found or expired. Please login again.'); const headers = new Headers(init.headers); headers.set('Authorization', `Bearer ${token}`); return fetch(url, { ...init, headers }) }
async function compressImage(file: File): Promise<File> { if (file.type === 'image/gif') { if (file.size > MAX_STORED_IMAGE_SIZE) throw new Error('GIF must not exceed 150 KB. Please choose a smaller image or use JPG/PNG/WEBP.'); return file } if (file.size <= MAX_STORED_IMAGE_SIZE && file.type === 'image/webp') return file; const bitmap = await createImageBitmap(file); const dimensions = [1200, 1000, 800, 700, 600, 500, 400]; const qualities = [0.82, 0.72, 0.62, 0.52, 0.42, 0.34, 0.28]; try { for (const maxDimension of dimensions) { const scale = Math.min(1, maxDimension / Math.max(bitmap.width, bitmap.height)); const width = Math.max(1, Math.round(bitmap.width * scale)); const height = Math.max(1, Math.round(bitmap.height * scale)); const canvas = document.createElement('canvas'); canvas.width = width; canvas.height = height; const ctx = canvas.getContext('2d'); if (!ctx) continue; ctx.drawImage(bitmap, 0, 0, width, height); for (const quality of qualities) { const blob = await new Promise<Blob | null>(r => canvas.toBlob(r, 'image/webp', quality)); if (blob && blob.size <= MAX_STORED_IMAGE_SIZE) return new File([blob], `${file.name.replace(/\.[^.]+$/, '')}.webp`, { type: 'image/webp', lastModified: Date.now() }) } } } finally { bitmap.close() } throw new Error('Image could not be compressed below 150 KB. Please choose a simpler or smaller image.') }

export function AdminNewsPage() {
  const [news, setNews] = useState<News[]>([]), [search, setSearch] = useState(''), [statusFilter, setStatusFilter] = useState('All'), [categoryFilter, setCategoryFilter] = useState('All'), [isModalOpen, setIsModalOpen] = useState(false), [editingNews, setEditingNews] = useState<News | null>(null), [form, setForm] = useState<NewsForm>(emptyForm), [imageFile, setImageFile] = useState<File | null>(null), [imagePreview, setImagePreview] = useState(''), [error, setError] = useState(''), [loading, setLoading] = useState(true), [saving, setSaving] = useState(false)
  async function loadNews() { try { setLoading(true); setError(''); const r = await fetch(`${API_BASE_URL}/api/news`, { cache: 'no-store' }); const result: ApiResponse<News[]> = await r.json(); if (!r.ok || !result.success) throw new Error(result.message || 'Gagal mengambil data news.'); setNews(result.data || []) } catch (e) { setError(e instanceof Error ? e.message : 'Gagal mengambil data news.') } finally { setLoading(false) } }
  useEffect(() => { loadNews() }, [])
  const categories = Array.from(new Set(news.map(i => i.category))); const filteredNews = useMemo(() => news.filter(i => { const q = search.trim().toLowerCase(); return (!q || i.title.toLowerCase().includes(q) || i.category.toLowerCase().includes(q) || i.author.toLowerCase().includes(q) || i.excerpt.toLowerCase().includes(q)) && (statusFilter === 'All' || i.status === statusFilter) && (categoryFilter === 'All' || i.category === categoryFilter) }), [news, search, statusFilter, categoryFilter]); const publishedCount = news.filter(i => i.status === 'Published').length; const draftCount = news.filter(i => i.status === 'Draft').length
  const resetImage = () => { setImageFile(null); setImagePreview('') }; const openAddModal = () => { setEditingNews(null); setForm({ ...emptyForm, date: new Date().toISOString().split('T')[0] }); resetImage(); setError(''); setIsModalOpen(true) }; const openEditModal = (item: News) => { setEditingNews(item); setForm({ title: item.title, category: item.category, author: item.author, excerpt: item.excerpt, content: item.content, date: item.date, status: item.status }); setImageFile(null); setImagePreview(item.image_url || ''); setError(''); setIsModalOpen(true) }; const closeModal = () => { if (saving) return; setIsModalOpen(false); setEditingNews(null); setForm(emptyForm); resetImage(); setError('') }
  function handleImageChange(e: React.ChangeEvent<HTMLInputElement>) { const file = e.target.files?.[0]; if (!file) return; if (!ALLOWED_IMAGE_TYPES.includes(file.type)) return setError('Image must be JPG, PNG, WEBP, or GIF.'); if (file.size > MAX_IMAGE_SIZE) return setError('Image size must not exceed 5 MB.'); setError(''); setImageFile(file); setImagePreview(URL.createObjectURL(file)) }
  async function handleSubmit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); setError(''); const title = form.title.trim(), author = form.author.trim(), excerpt = form.excerpt.trim(), content = form.content.trim(); if (!title) return setError('News title is required.'); if (!author) return setError('Author is required.'); if (!excerpt) return setError('Excerpt is required.'); if (!content) return setError('Content is required.'); if (!form.date) return setError('Publication date is required.'); try { setSaving(true); const fd = new FormData(); fd.append('title', title); fd.append('category', form.category); fd.append('author', author); fd.append('excerpt', excerpt); fd.append('content', content); fd.append('date', form.date); fd.append('status', form.status); if (imageFile) fd.append('image', await compressImage(imageFile)); const editing = !!editingNews; const url = editing ? `${API_BASE_URL}/api/news/${editingNews!.id}` : `${API_BASE_URL}/api/news`; const r = await adminFetch(url, { method: editing ? 'PUT' : 'POST', body: fd }); const result: ApiResponse<News> = await r.json(); if (!r.ok || !result.success) throw new Error(result.message || 'Gagal menyimpan news.'); if (!result.data) throw new Error('News was saved but no data was returned.'); setNews(current => editing ? current.map(i => i.id === result.data!.id ? result.data! : i) : [result.data!, ...current]); closeModal() } catch (e) { setError(e instanceof Error ? e.message : 'Gagal menyimpan news.') } finally { setSaving(false) } }
  async function handleDelete(id: number) { const item = news.find(i => i.id === id); if (!item || !window.confirm(`Are you sure you want to delete "${item.title}"?`)) return; try { const r = await adminFetch(`${API_BASE_URL}/api/news/${id}`, { method: 'DELETE' }); const result: ApiResponse<unknown> = await r.json(); if (!r.ok || !result.success) throw new Error(result.message || 'Gagal menghapus news.'); setNews(current => current.filter(i => i.id !== id)) } catch (e) { setError(e instanceof Error ? e.message : 'Gagal menghapus news.') } }
  function formatDate(date: string) { return new Intl.DateTimeFormat('id-ID', { day: '2-digit', month: 'short', year: 'numeric' }).format(new Date(`${date}T00:00:00`)) }
  return <div className="space-y-8"><div className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><p className="text-sm text-text-muted">Admin Panel</p><h1 className="mt-1 font-display text-3xl font-bold text-text-primary">News</h1><p className="mt-2 text-sm text-text-secondary">Manage news articles and website publications.</p></div><button onClick={openAddModal} className="inline-flex items-center gap-2 rounded-lg bg-brand-primary px-4 py-2.5 text-sm font-semibold text-white hover:bg-brand-secondary"><Plus className="h-4 w-4" />Add News</button></div>
    {error && !isModalOpen && <div className="rounded-lg border border-red-500/20 bg-red-500/10 px-4 py-3 text-sm text-red-400">{error}</div>}
    <div className="grid grid-cols-1 gap-4 md:grid-cols-3"><StatCard label="Total News" value={String(news.length)} /><StatCard label="Published" value={String(publishedCount)} /><StatCard label="Draft" value={String(draftCount)} /></div>
    <div className="rounded-xl border border-border-default bg-bg-surface p-5"><div className="grid gap-4 md:grid-cols-[1fr_200px_200px]"><div className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-text-muted" /><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search news..." className="w-full rounded-lg border border-border-default bg-bg-base py-3 pl-10 pr-4 text-sm text-text-primary outline-none focus:border-brand-primary" /></div><select value={categoryFilter} onChange={e => setCategoryFilter(e.target.value)} className="rounded-lg border border-border-default bg-bg-base px-4 py-3 text-sm text-text-primary"><option>All</option>{categories.map(c => <option key={c}>{c}</option>)}</select><select value={statusFilter} onChange={e => setStatusFilter(e.target.value)} className="rounded-lg border border-border-default bg-bg-base px-4 py-3 text-sm text-text-primary"><option>All</option><option>Published</option><option>Draft</option></select></div></div>
    <div className="overflow-hidden rounded-xl border border-border-default bg-bg-surface"><div className="overflow-x-auto"><table className="w-full min-w-[1100px] text-left text-sm"><thead className="border-b border-border-default bg-bg-base"><tr>{['Article', 'Category', 'Author', 'Date', 'Status', 'Actions'].map(h => <th key={h} className="px-6 py-4 font-semibold text-text-primary">{h}</th>)}</tr></thead><tbody>{loading ? <tr><td colSpan={6} className="px-6 py-16 text-center text-text-muted">Loading news...</td></tr> : filteredNews.length === 0 ? <tr><td colSpan={6} className="px-6 py-16 text-center text-text-muted">No news articles found.</td></tr> : filteredNews.map(item => <tr key={item.id} className="border-b border-border-default last:border-0"><td className="px-6 py-4"><div className="flex items-center gap-3"><div className="h-14 w-20 shrink-0 overflow-hidden rounded-lg bg-bg-base">{item.image_url ? <img src={item.image_url} alt={item.title} className="h-full w-full object-cover" /> : <div className="flex h-full items-center justify-center"><FileText className="h-5 w-5 text-text-muted" /></div>}</div><div className="max-w-md"><p className="font-medium text-text-primary">{item.title}</p><p className="mt-1 truncate text-xs text-text-muted">{item.excerpt}</p></div></div></td><td className="px-6 py-4 text-text-secondary">{item.category}</td><td className="px-6 py-4 text-text-secondary">{item.author}</td><td className="px-6 py-4 text-text-secondary">{formatDate(item.date)}</td><td className="px-6 py-4"><span className={`rounded-full px-3 py-1 text-xs ${item.status === 'Published' ? 'bg-green-400/10 text-green-400' : 'bg-yellow-400/10 text-yellow-400'}`}>{item.status}</span></td><td className="px-6 py-4"><div className="flex gap-2"><button onClick={() => openEditModal(item)} className="rounded-lg border border-border-default p-2 text-text-muted hover:text-text-primary"><Edit className="h-4 w-4" /></button><button onClick={() => handleDelete(item.id)} className="rounded-lg border border-border-default p-2 text-red-400 hover:bg-red-400/10"><Trash2 className="h-4 w-4" /></button></div></td></tr>)}</tbody></table></div></div>
    {isModalOpen && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 px-4 py-6"><div className="max-h-[90vh] w-full max-w-3xl overflow-y-auto rounded-2xl border border-border-default bg-bg-surface shadow-2xl"><div className="flex items-center justify-between border-b border-border-default px-6 py-5"><div><h2 className="font-display text-xl font-bold text-text-primary">{editingNews ? 'Edit News' : 'Add News'}</h2><p className="mt-1 text-sm text-text-muted">{editingNews ? 'Update news article information.' : 'Create a new news article.'}</p></div><button onClick={closeModal} disabled={saving} className="rounded-lg p-2 text-text-muted hover:bg-bg-base"><X className="h-5 w-5" /></button></div><form onSubmit={handleSubmit} className="space-y-5 p-6">{error && <div className="rounded-lg border border-red-500/20 bg-red-500/10 px-4 py-3 text-sm text-red-400">{error}</div>}
      <Field label="Title"><input value={form.title} onChange={e => setForm({ ...form, title: e.target.value })} placeholder="News title" className={inputClass} /></Field>
      <div className="grid gap-5 md:grid-cols-2"><Field label="Category"><select value={form.category} onChange={e => setForm({ ...form, category: e.target.value })} className={inputClass}><option>Company</option><option>Behind The Scenes</option><option>Tips</option><option>Announcement</option><option>Technology</option><option>Creative</option></select></Field><Field label="Publication Date"><input type="date" value={form.date} onChange={e => setForm({ ...form, date: e.target.value })} className={inputClass} /></Field></div>
      <Field label="Author"><input value={form.author} onChange={e => setForm({ ...form, author: e.target.value })} placeholder="Admin" className={inputClass} /></Field>
      <div><label className="mb-2 block text-sm font-medium text-text-primary">News Cover Image</label><div className="flex items-center gap-4"><div className="h-28 w-44 overflow-hidden rounded-xl border border-border-default bg-bg-base">{imagePreview ? <img src={imagePreview} alt="News preview" className="h-full w-full object-cover" /> : <div className="flex h-full flex-col items-center justify-center text-text-muted"><ImagePlus className="h-7 w-7" /><span className="mt-2 text-xs">No image</span></div>}</div><div><label className="inline-flex cursor-pointer items-center gap-2 rounded-lg border border-border-default px-4 py-2.5 text-sm font-medium text-text-primary hover:bg-bg-base"><ImagePlus className="h-4 w-4" />Choose Image<input type="file" accept="image/jpeg,image/png,image/webp,image/gif" onChange={handleImageChange} disabled={saving} className="sr-only" /></label><p className="mt-2 text-xs text-text-muted">JPG, PNG, WEBP, GIF. Max 5 MB; stored image is compressed to 150 KB.</p>{imageFile && <p className="mt-1 max-w-xs truncate text-xs text-text-secondary">{imageFile.name}</p>}</div></div></div>
      <Field label="Excerpt"><textarea rows={3} value={form.excerpt} onChange={e => setForm({ ...form, excerpt: e.target.value })} placeholder="Short summary of the article..." className={inputClass + ' resize-none'} /></Field><Field label="Content"><textarea rows={8} value={form.content} onChange={e => setForm({ ...form, content: e.target.value })} placeholder="Write the complete article content..." className={inputClass + ' resize-none'} /></Field><Field label="Status"><select value={form.status} onChange={e => setForm({ ...form, status: e.target.value as 'Published' | 'Draft' })} className={inputClass}><option>Published</option><option>Draft</option></select></Field>
      <div className="flex justify-end gap-3 border-t border-border-default pt-5"><button type="button" onClick={closeModal} disabled={saving} className="rounded-lg border border-border-default px-5 py-2.5 text-sm text-text-secondary">Cancel</button><button type="submit" disabled={saving} className="rounded-lg bg-brand-primary px-5 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{saving ? 'Saving...' : editingNews ? 'Save Changes' : 'Create News'}</button></div>
    </form></div></div>}
  </div>
}
const inputClass = 'w-full rounded-lg border border-border-default bg-bg-base px-4 py-3 text-sm text-text-primary outline-none focus:border-brand-primary'
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div><label className="mb-2 block text-sm font-medium text-text-primary">{label}</label>{children}</div> }
function StatCard({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-border-default bg-bg-surface p-5"><div className="mb-3 flex items-center gap-2 text-brand-primary"><FileText className="h-5 w-5" /><span className="text-sm">{label}</span></div><p className="text-2xl font-bold text-text-primary">{value}</p></div> }
