import { useEffect, useMemo, useState } from 'react'
import { Plus, Search, Users, UserRound, Crown, BriefcaseBusiness, Mic2, MoreHorizontal, Pencil, Trash2, X, Power } from 'lucide-react'
import { del, get, post, put } from '@/utils/businessApi'

type Role = 'Founder' | 'Co-Founder' | 'Team' | 'Talent'; type Status = 'Active' | 'Inactive'
interface Member { id: number; name: string; role: Role; position: string; email: string; status: Status; joinedAt: string }
const roleConfig: any = { Founder: { icon: Crown, className: 'bg-purple-500/10 text-purple-400' }, 'Co-Founder': { icon: Crown, className: 'bg-pink-500/10 text-pink-400' }, Team: { icon: BriefcaseBusiness, className: 'bg-blue-500/10 text-blue-400' }, Talent: { icon: Mic2, className: 'bg-cyan-500/10 text-cyan-400' } }
export function AdminMembersPage() {
    const [members, setMembers] = useState<Member[]>([]), [search, setSearch] = useState(''), [roleFilter, setRoleFilter] = useState<'All' | Role>('All'), [show, setShow] = useState(false), [editing, setEditing] = useState<Member | null>(null), [menu, setMenu] = useState<number | null>(null), [loading, setLoading] = useState(true), [error, setError] = useState('')
    const load = async () => { try { setLoading(true); setError(''); setMembers((await get<{ data: Member[] }>('/api/admin/members')).data) } catch (e) { setError(e instanceof Error ? e.message : 'Failed to load members') } finally { setLoading(false) } }; useEffect(() => { load() }, [])
    const filtered = useMemo(() => members.filter(m => (m.name + ' ' + m.email + ' ' + m.position).toLowerCase().includes(search.toLowerCase()) && (roleFilter === 'All' || m.role === roleFilter)), [members, search, roleFilter])
    const save = async (v: Member) => { try { if (editing) await put(`/api/admin/members/${v.id}`, v); else await post('/api/admin/members', v); setShow(false); setEditing(null); await load() } catch (e) { alert(e instanceof Error ? e.message : 'Failed to save member') } }
    const remove = async (id: number) => { if (!confirm('Hapus member ini?')) return; try { await del(`/api/admin/members/${id}`); await load() } catch (e) { alert(e instanceof Error ? e.message : 'Failed to delete member') } }
    const toggle = async (m: Member) => { try { await put(`/api/admin/members/${m.id}`, { status: m.status === 'Active' ? 'Inactive' : 'Active' }); await load() } catch (e) { alert(e instanceof Error ? e.message : 'Failed to update status') } }
    return <div className="space-y-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><h2 className="text-2xl font-bold text-text-primary">Members</h2><p className="mt-1 text-sm text-text-muted">Manage founders, team members, and 39Production talent.</p></div><button onClick={() => { setEditing(null); setShow(true) }} className="inline-flex items-center justify-center gap-2 rounded-lg bg-brand-primary px-4 py-2.5 text-sm font-semibold text-white"><Plus className="h-4 w-4" />Add Member</button></div>
        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[[Users, 'Total Members', members.length], [UserRound, 'Active', members.filter(x => x.status === 'Active').length], [Mic2, 'Talent', members.filter(x => x.role === 'Talent').length], [Crown, 'Founding Team', members.filter(x => x.role === 'Founder' || x.role === 'Co-Founder').length]].map(([Icon, label, value]: any) => <Stat key={label} icon={Icon} label={label} value={value} />)}</div>
        <div className="rounded-xl border border-border-default bg-bg-surface p-4"><div className="flex flex-col gap-3 md:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-text-muted" /><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search members..." className="w-full rounded-lg border border-border-default bg-bg-base py-2.5 pl-10 pr-4 text-sm text-text-primary outline-none focus:border-brand-primary" /></div><select value={roleFilter} onChange={e => setRoleFilter(e.target.value as any)} className="rounded-lg border border-border-default bg-bg-base px-4 py-2.5 text-sm text-text-primary"><option>All</option><option>Founder</option><option>Co-Founder</option><option>Team</option><option>Talent</option></select></div></div>
        {error && <div className="rounded-xl border border-red-500/20 bg-red-500/5 p-4 text-sm text-red-400">{error}</div>}
        <div className="overflow-hidden rounded-xl border border-border-default bg-bg-surface"><div className="overflow-x-auto"><table className="w-full min-w-[850px]"><thead><tr className="border-b border-border-default bg-bg-elevated/50">{['Member', 'Role', 'Position', 'Status', 'Action'].map((h, i) => <th key={h} className={`px-5 py-4 text-xs font-semibold uppercase tracking-wider text-text-muted ${i === 4 ? 'text-right' : 'text-left'}`}>{h}</th>)}</tr></thead><tbody>{loading ? <tr><td colSpan={5} className="p-12 text-center text-sm text-text-muted">Loading...</td></tr> : filtered.map(m => { const c = roleConfig[m.role]; const Icon = c.icon; return <tr key={m.id} className="border-b border-border-default last:border-0 hover:bg-bg-elevated/30"><td className="px-5 py-4"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-full bg-brand-primary/10 text-brand-primary"><Icon className="h-5 w-5" /></div><div><p className="font-medium text-text-primary">{m.name}</p><p className="text-xs text-text-muted">{m.email}</p></div></div></td><td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-medium ${c.className}`}>{m.role}</span></td><td className="px-5 py-4 text-sm text-text-secondary">{m.position}</td><td className="px-5 py-4"><span className={`inline-flex items-center gap-1.5 text-xs font-medium ${m.status === 'Active' ? 'text-green-400' : 'text-text-muted'}`}><span className="h-1.5 w-1.5 rounded-full bg-current" />{m.status}</span></td><td className="relative px-5 py-4 text-right"><button onClick={() => setMenu(menu === m.id ? null : m.id)} className="rounded-lg p-2 text-text-muted hover:bg-bg-elevated"><MoreHorizontal className="h-4 w-4" /></button>{menu === m.id && <div className="absolute right-5 top-12 z-20 w-40 rounded-lg border border-border-default bg-bg-surface p-1 text-left shadow-xl"><button onClick={() => { setEditing(m); setShow(true); setMenu(null) }} className="flex w-full items-center gap-2 rounded-md px-3 py-2 text-sm text-text-secondary hover:bg-bg-elevated"><Pencil className="h-4 w-4" />Edit</button><button onClick={() => { toggle(m); setMenu(null) }} className="flex w-full items-center gap-2 rounded-md px-3 py-2 text-sm text-text-secondary hover:bg-bg-elevated"><Power className="h-4 w-4" />{m.status === 'Active' ? 'Deactivate' : 'Activate'}</button><button onClick={() => { remove(m.id); setMenu(null) }} className="flex w-full items-center gap-2 rounded-md px-3 py-2 text-sm text-red-400 hover:bg-red-500/10"><Trash2 className="h-4 w-4" />Delete</button></div>}</td></tr> })}</tbody></table></div>{!loading && !filtered.length && <div className="p-12 text-center text-sm text-text-muted">No members found.</div>}</div>
        {show && <MemberModal member={editing} onClose={() => { setShow(false); setEditing(null) }} onSave={save} />}</div>
}
function Stat({ icon: Icon, label, value }: { icon: any; label: string; value: number }) { return <div className="rounded-xl border border-border-default bg-bg-surface p-5"><div className="flex items-center justify-between"><div><p className="text-sm text-text-muted">{label}</p><p className="mt-2 text-2xl font-bold text-text-primary">{value}</p></div><div className="rounded-lg bg-brand-primary/10 p-3 text-brand-primary"><Icon className="h-5 w-5" /></div></div></div> }
function MemberModal({ member, onClose, onSave }: { member: Member | null; onClose: () => void; onSave: (m: Member) => void }) { const [v, setV] = useState<any>(member || { name: '', role: 'Team', position: '', email: '', status: 'Active' }); return <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/70 p-4 backdrop-blur-sm"><div className="w-full max-w-lg rounded-2xl border border-border-default bg-bg-surface shadow-2xl"><div className="flex items-center justify-between border-b border-border-default p-5"><div><h3 className="font-semibold text-text-primary">{member ? 'Edit Member' : 'Add Member'}</h3><p className="mt-1 text-xs text-text-muted">Manage internal 39Production members.</p></div><button onClick={onClose}><X className="h-5 w-5 text-text-muted" /></button></div><form onSubmit={e => { e.preventDefault(); if (!v.name || !v.email || !v.position) return; onSave(v) }} className="space-y-4 p-5">{[['Name', 'name', 'text'], ['Position', 'position', 'text'], ['Email', 'email', 'email']].map(([l, k, t]) => <label key={k} className="block"><span className="mb-1.5 block text-xs font-medium text-text-secondary">{l}</span><input required type={t} value={v[k]} onChange={e => setV({ ...v, [k]: e.target.value })} className="w-full rounded-lg border border-border-default bg-bg-base px-3 py-2.5 text-sm text-text-primary" /></label>)}<div className="grid gap-4 sm:grid-cols-2"><label><span className="mb-1.5 block text-xs font-medium text-text-secondary">Role</span><select value={v.role} onChange={e => setV({ ...v, role: e.target.value })} className="w-full rounded-lg border border-border-default bg-bg-base px-3 py-2.5 text-sm text-text-primary"><option>Founder</option><option>Co-Founder</option><option>Team</option><option>Talent</option></select></label><label><span className="mb-1.5 block text-xs font-medium text-text-secondary">Status</span><select value={v.status} onChange={e => setV({ ...v, status: e.target.value })} className="w-full rounded-lg border border-border-default bg-bg-base px-3 py-2.5 text-sm text-text-primary"><option>Active</option><option>Inactive</option></select></label></div><div className="flex justify-end gap-3"><button type="button" onClick={onClose} className="rounded-lg border border-border-default px-4 py-2.5 text-sm text-text-secondary">Cancel</button><button className="rounded-lg bg-brand-primary px-4 py-2.5 text-sm font-semibold text-white">Save Member</button></div></form></div></div> }
